In [1]:
import pandas as pd
import numpy as np

In [2]:
# Reading csv file
IMDB_movies = pd.read_csv('IMDB_movies_and_ratings.csv')
# Dropping unneeded columns
IMDB_movies = IMDB_movies.drop(columns = ['Unnamed: 0', 'original_title','non_us_voters_rating', 'non_us_voters_votes', 'imdb_title_id', 'date_published', 'top1000_voters_rating', 
                                          'top1000_voters_votes', 'males_0age_avg_vote', 'males_0age_votes',
                                          'males_18age_avg_vote', 'males_18age_votes', 'males_30age_avg_vote', 'males_30age_votes', 'males_45age_avg_vote', 'males_45age_votes',
                                         'females_0age_avg_vote', 'females_0age_votes', 'females_18age_avg_vote', 'females_18age_votes', 'females_30age_avg_vote',
                                         'females_30age_votes', 'females_45age_avg_vote', 'females_45age_votes'])
IMDB_movies.head()

,title,year,genre,duration,country,language,director,writer,production_company,actors,...,allgenders_30age_avg_vote,allgenders_30age_votes,allgenders_45age_avg_vote,allgenders_45age_votes,males_allages_avg_vote,males_allages_votes,females_allages_avg_vote,females_allages_votes,us_voters_rating,us_voters_votes
0,Metropolis,1927,"Drama, Sci-Fi",153,Germany,German,Fritz Lang,"Thea von Harbou, Thea von Harbou",Universum Film (UFA),"Alfred Abel, Gustav Fröhlich, Rudolf Klein-Rog...",...,8.2,58194.0,8.3,23166.0,8.3,94002.0,8.3,18799.0,8.3,30678.0
1,City Lights,1931,"Comedy, Drama, Romance",87,USA,English,Charles Chaplin,Charles Chaplin,Charles Chaplin Productions,"Virginia Cherrill, Florence Lee, Harry Myers, ...",...,8.5,53607.0,8.5,19875.0,8.5,99110.0,8.5,17067.0,8.5,26265.0
2,Modern Times,1936,"Comedy, Drama, Family",87,USA,English,Charles Chaplin,Charles Chaplin,Charles Chaplin Productions,"Charles Chaplin, Paulette Goddard, Henry Bergm...",...,8.5,68964.0,8.5,23726.0,8.5,127668.0,8.5,22701.0,8.5,28002.0
3,Snow White and the Seven Dwarfs,1937,"Animation, Family, Fantasy",83,USA,English,"William Cottrell, David Hand","Jacob Grimm, Wilhelm Grimm",Walt Disney Productions,"Roy Atwell, Stuart Buchanan, Adriana Caselotti...",...,7.5,60524.0,7.9,16737.0,7.6,86831.0,7.7,43926.0,7.7,37903.0
4,Gone with the Wind,1939,"Drama, History, Romance",238,USA,English,"Victor Fleming, George Cukor","Margaret Mitchell, Sidney Howard",Selznick International Pictures,"Thomas Mitchell, Barbara O'Neil, Vivien Leigh,...",...,8.1,103642.0,8.2,48047.0,8.0,135179.0,8.5,70826.0,8.2,63770.0

In [3]:
# Adding positive votes, neutral votes, and negative votes columns
IMDB_movies['positive_votes'] = IMDB_movies['votes_10'] + IMDB_movies['votes_9'] + IMDB_movies['votes_8'] + IMDB_movies['votes_7']
IMDB_movies['neutral_votes'] = IMDB_movies['votes_6'] + IMDB_movies['votes_5'] + IMDB_movies['votes_4']
IMDB_movies['negative_votes'] = IMDB_movies['votes_3'] + IMDB_movies['votes_2'] + IMDB_movies['votes_1']
# Adding percentage of positive reviews column
IMDB_movies['percentage_of_positive_reviews'] = (IMDB_movies['positive_votes']/(IMDB_movies['positive_votes']+IMDB_movies['neutral_votes']+
  IMDB_movies['negative_votes'])).round(2)                                         
IMDB_movies.head()

,title,year,genre,duration,country,language,director,writer,production_company,actors,...,males_allages_avg_vote,males_allages_votes,females_allages_avg_vote,females_allages_votes,us_voters_rating,us_voters_votes,positive_votes,neutral_votes,negative_votes,percentage_of_positive_reviews
0,Metropolis,1927,"Drama, Sci-Fi",153,Germany,German,Fritz Lang,"Thea von Harbou, Thea von Harbou",Universum Film (UFA),"Alfred Abel, Gustav Fröhlich, Rudolf Klein-Rog...",...,8.3,94002.0,8.3,18799.0,8.3,30678.0,127571,15050,5775,0.86
1,City Lights,1931,"Comedy, Drama, Romance",87,USA,English,Charles Chaplin,Charles Chaplin,Charles Chaplin Productions,"Virginia Cherrill, Florence Lee, Harry Myers, ...",...,8.5,99110.0,8.5,17067.0,8.5,26265.0,137344,10919,4453,0.90
2,Modern Times,1936,"Comedy, Drama, Family",87,USA,English,Charles Chaplin,Charles Chaplin,Charles Chaplin Productions,"Charles Chaplin, Paulette Goddard, Henry Bergm...",...,8.5,127668.0,8.5,22701.0,8.5,28002.0,180178,12840,4951,0.91
3,Snow White and the Seven Dwarfs,1937,"Animation, Family, Fantasy",83,USA,English,"William Cottrell, David Hand","Jacob Grimm, Wilhelm Grimm",Walt Disney Productions,"Roy Atwell, Stuart Buchanan, Adriana Caselotti...",...,7.6,86831.0,7.7,43926.0,7.7,37903.0,137135,28600,3000,0.81
4,Gone with the Wind,1939,"Drama, History, Romance",238,USA,English,"Victor Fleming, George Cukor","Margaret Mitchell, Sidney Howard",Selznick International Pictures,"Thomas Mitchell, Barbara O'Neil, Vivien Leigh,...",...,8.0,135179.0,8.5,70826.0,8.2,63770.0,230519,29565,9580,0.85

In [4]:
# Creating sentiment column from percentage of positive reviews (if more than 60% of reviews are positive then good movie)
IMDB_movies['overall_eval'] = np.where(IMDB_movies['percentage_of_positive_reviews']>=0.60,'good', 'bad')
IMDB_movies.head()

,title,year,genre,duration,country,language,director,writer,production_company,actors,...,males_allages_votes,females_allages_avg_vote,females_allages_votes,us_voters_rating,us_voters_votes,positive_votes,neutral_votes,negative_votes,percentage_of_positive_reviews,overall_eval
0,Metropolis,1927,"Drama, Sci-Fi",153,Germany,German,Fritz Lang,"Thea von Harbou, Thea von Harbou",Universum Film (UFA),"Alfred Abel, Gustav Fröhlich, Rudolf Klein-Rog...",...,94002.0,8.3,18799.0,8.3,30678.0,127571,15050,5775,0.86,good
1,City Lights,1931,"Comedy, Drama, Romance",87,USA,English,Charles Chaplin,Charles Chaplin,Charles Chaplin Productions,"Virginia Cherrill, Florence Lee, Harry Myers, ...",...,99110.0,8.5,17067.0,8.5,26265.0,137344,10919,4453,0.90,good
2,Modern Times,1936,"Comedy, Drama, Family",87,USA,English,Charles Chaplin,Charles Chaplin,Charles Chaplin Productions,"Charles Chaplin, Paulette Goddard, Henry Bergm...",...,127668.0,8.5,22701.0,8.5,28002.0,180178,12840,4951,0.91,good
3,Snow White and the Seven Dwarfs,1937,"Animation, Family, Fantasy",83,USA,English,"William Cottrell, David Hand","Jacob Grimm, Wilhelm Grimm",Walt Disney Productions,"Roy Atwell, Stuart Buchanan, Adriana Caselotti...",...,86831.0,7.7,43926.0,7.7,37903.0,137135,28600,3000,0.81,good
4,Gone with the Wind,1939,"Drama, History, Romance",238,USA,English,"Victor Fleming, George Cukor","Margaret Mitchell, Sidney Howard",Selznick International Pictures,"Thomas Mitchell, Barbara O'Neil, Vivien Leigh,...",...,135179.0,8.5,70826.0,8.2,63770.0,230519,29565,9580,0.85,good

In [5]:
# Converting good and bad values into dummies
IMDB_movies['overall_eval']=IMDB_movies['overall_eval'].str.get_dummies()

In [6]:
IMDB_movies['overall_eval'].head()

0    0
1    0
2    0
3    0
4    0
Name: overall_eval, dtype: int64

In [9]:
# Setting good = 1 and bad = 0
IMDB_movies['overall_eval'] = IMDB_movies['overall_eval'].replace({0:1, 1:0})
IMDB_movies['overall_eval']

0       1
1       1
2       1
3       1
4       1
       ..
4176    0
4177    1
4178    1
4179    0
4180    0
Name: overall_eval, Length: 4181, dtype: int64

In [ ]:
# Formatting percentage of positive reviews (2 decimals and %)
# IMDB_movies['percentage_of_positive_reviews']=IMDB_movies['percentage_of_positive_reviews'].map('{:.2f}%'.format)
# IMDB_movies.head()

In [10]:
# Renaming columns
IMDB_movies = IMDB_movies.rename(columns={'avg_vote':'IMDB_rating', 'allgenders_0age_avg_vote':'avg_rating_<18yrs', 'allgenders_0age_votes':'votes_<18yrs',
                                  'allgenders_18age_avg_vote': 'avg_rating_18-30yrs','allgenders_18age_votes':'votes_18-30yrs', 'allgenders_30age_avg_vote':'avg_rating_30-45yrs',
                                         'allgenders_30age_votes': 'votes_30-45yrs','allgenders_45age_avg_vote': 'avg_rating_>45yrs','allgenders_45age_votes':'votes_>45yrs',
                                         'females_allages_votes':'female_votes','males_allages_votes':'male_votes', 'females_allages_avg_vote':'female_avg_rating', 'males_allages_avg_vote':'male_avg_rating'})
IMDB_movies.head()

,title,year,genre,duration,country,language,director,writer,production_company,actors,...,male_votes,female_avg_rating,female_votes,us_voters_rating,us_voters_votes,positive_votes,neutral_votes,negative_votes,percentage_of_positive_reviews,overall_eval
0,Metropolis,1927,"Drama, Sci-Fi",153,Germany,German,Fritz Lang,"Thea von Harbou, Thea von Harbou",Universum Film (UFA),"Alfred Abel, Gustav Fröhlich, Rudolf Klein-Rog...",...,94002.0,8.3,18799.0,8.3,30678.0,127571,15050,5775,0.86,1
1,City Lights,1931,"Comedy, Drama, Romance",87,USA,English,Charles Chaplin,Charles Chaplin,Charles Chaplin Productions,"Virginia Cherrill, Florence Lee, Harry Myers, ...",...,99110.0,8.5,17067.0,8.5,26265.0,137344,10919,4453,0.90,1
2,Modern Times,1936,"Comedy, Drama, Family",87,USA,English,Charles Chaplin,Charles Chaplin,Charles Chaplin Productions,"Charles Chaplin, Paulette Goddard, Henry Bergm...",...,127668.0,8.5,22701.0,8.5,28002.0,180178,12840,4951,0.91,1
3,Snow White and the Seven Dwarfs,1937,"Animation, Family, Fantasy",83,USA,English,"William Cottrell, David Hand","Jacob Grimm, Wilhelm Grimm",Walt Disney Productions,"Roy Atwell, Stuart Buchanan, Adriana Caselotti...",...,86831.0,7.7,43926.0,7.7,37903.0,137135,28600,3000,0.81,1
4,Gone with the Wind,1939,"Drama, History, Romance",238,USA,English,"Victor Fleming, George Cukor","Margaret Mitchell, Sidney Howard",Selznick International Pictures,"Thomas Mitchell, Barbara O'Neil, Vivien Leigh,...",...,135179.0,8.5,70826.0,8.2,63770.0,230519,29565,9580,0.85,1

In [ ]:
# Male/Female Votes Distribution
# IMDB_movies['percentage_female'] = (IMDB_movies['female_votes']/(IMDB_movies['female_votes']+IMDB_movies['male_votes'])).round(2)
# IMDB_movies['percentage_male'] = (IMDB_movies['male_votes']/(IMDB_movies['female_votes']+IMDB_movies['male_votes'])).round(2)
# IMDB_movies.head()

In [ ]:
# New columns age percentages
# IMDB_movies['percentage<18yrs'] = (IMDB_movies['number_votes_<18yrs']/(IMDB_movies['number_votes_<18yrs']+
#                                 IMDB_movies['number_votes_18-30yrs']+IMDB_movies['number_votes_30-45yrs']+IMDB_movies['number_votes_>45yrs'])).round(2) 
# IMDB_movies['percentage18-30yrs'] = (IMDB_movies['number_votes_18-30yrs']/(IMDB_movies['number_votes_<18yrs']+
#                                 IMDB_movies['number_votes_18-30yrs']+IMDB_movies['number_votes_30-45yrs']+IMDB_movies['number_votes_>45yrs'])).round(2) 
# IMDB_movies['percentage30-45yrs'] = (IMDB_movies['number_votes_30-45yrs']/(IMDB_movies['number_votes_<18yrs']+
#                                 IMDB_movies['number_votes_18-30yrs']+IMDB_movies['number_votes_30-45yrs']+IMDB_movies['number_votes_>45yrs'])).round(2) 
# IMDB_movies['percentage>45yrs'] = (IMDB_movies['number_votes_>45yrs']/(IMDB_movies['number_votes_<18yrs']+
#                                 IMDB_movies['number_votes_18-30yrs']+IMDB_movies['number_votes_30-45yrs']+IMDB_movies['number_votes_>45yrs'])).round(2)

In [12]:
# Pulling only rows needed
# IMDB_movies_analysis = IMDB_movies[['title','year','country','language','duration','genre','production_company','description','budget',
#                                     'usa_gross_income','worlwide_gross_income','IMDB_rating','metascore','reviews_from_users',
#                                     'reviews_from_critics','female_avg_rating','male_avg_rating','female_votes','male_votes','votes',
#                                     'percentage_female','percentage_male','percentage<18yrs','percentage18-30yrs','percentage30-45yrs',
#                                     'percentage>45yrs','positive_votes','neutral_votes','negative_votes',
#                                     'percentage_of_positive_reviews', 'sentiment']]
IMDB_movies_analysis = IMDB_movies[['title','year','country','language','duration','genre','director','production_company','description','budget',
                                    'usa_gross_income','worlwide_gross_income','IMDB_rating','metascore','reviews_from_users', 'votes',
                                    'reviews_from_critics','female_avg_rating','male_avg_rating','female_votes','male_votes','avg_rating_<18yrs',
                                    'votes_<18yrs','avg_rating_18-30yrs','votes_18-30yrs', 'avg_rating_30-45yrs',
                                    'votes_30-45yrs','avg_rating_>45yrs','votes_>45yrs','positive_votes','neutral_votes','negative_votes',
                                    'percentage_of_positive_reviews', 'overall_eval']]



IMDB_movies_analysis.head()

,title,year,country,language,duration,genre,director,production_company,description,budget,...,votes_18-30yrs,avg_rating_30-45yrs,votes_30-45yrs,avg_rating_>45yrs,votes_>45yrs,positive_votes,neutral_votes,negative_votes,percentage_of_positive_reviews,overall_eval
0,Metropolis,1927,Germany,German,153,"Drama, Sci-Fi",Fritz Lang,Universum Film (UFA),In a futuristic city sharply divided between t...,DEM 6000000,...,28391.0,8.2,58194.0,8.3,23166.0,127571,15050,5775,0.86,1
1,City Lights,1931,USA,English,87,"Comedy, Drama, Romance",Charles Chaplin,Charles Chaplin Productions,"With the aid of a wealthy erratic tippler, a d...",$ 1500000,...,38349.0,8.5,53607.0,8.5,19875.0,137344,10919,4453,0.90,1
2,Modern Times,1936,USA,English,87,"Comedy, Drama, Family",Charles Chaplin,Charles Chaplin Productions,The Tramp struggles to live in modern industri...,$ 1500000,...,51346.0,8.5,68964.0,8.5,23726.0,180178,12840,4951,0.91,1
3,Snow White and the Seven Dwarfs,1937,USA,English,83,"Animation, Family, Fantasy","William Cottrell, David Hand",Walt Disney Productions,Exiled into the dangerous forest by her wicked...,$ 1499000,...,48726.0,7.5,60524.0,7.9,16737.0,137135,28600,3000,0.81,1
4,Gone with the Wind,1939,USA,English,238,"Drama, History, Romance","Victor Fleming, George Cukor",Selznick International Pictures,A manipulative woman and a roguish man conduct...,$ 3977000,...,47171.0,8.1,103642.0,8.2,48047.0,230519,29565,9580,0.85,1

In [13]:
# Splitting genre into separate columns
IMDB_movies_analysis[['genre_1','genre_2', 'genre_3']] = IMDB_movies_analysis['genre'].str.split(",", expand=True)
IMDB_movies_analysis

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pandas/core/frame.py:3509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,title,year,country,language,duration,genre,director,production_company,description,budget,...,avg_rating_>45yrs,votes_>45yrs,positive_votes,neutral_votes,negative_votes,percentage_of_positive_reviews,overall_eval,genre_1,genre_2,genre_3
0,Metropolis,1927,Germany,German,153,"Drama, Sci-Fi",Fritz Lang,Universum Film (UFA),In a futuristic city sharply divided between t...,DEM 6000000,...,8.3,23166.0,127571,15050,5775,0.86,1,Drama,Sci-Fi,None
1,City Lights,1931,USA,English,87,"Comedy, Drama, Romance",Charles Chaplin,Charles Chaplin Productions,"With the aid of a wealthy erratic tippler, a d...",$ 1500000,...,8.5,19875.0,137344,10919,4453,0.90,1,Comedy,Drama,Romance
2,Modern Times,1936,USA,English,87,"Comedy, Drama, Family",Charles Chaplin,Charles Chaplin Productions,The Tramp struggles to live in modern industri...,$ 1500000,...,8.5,23726.0,180178,12840,4951,0.91,1,Comedy,Drama,Family
3,Snow White and the Seven Dwarfs,1937,USA,English,83,"Animation, Family, Fantasy","William Cottrell, David Hand",Walt Disney Productions,Exiled into the dangerous forest by her wicked...,$ 1499000,...,7.9,16737.0,137135,28600,3000,0.81,1,Animation,Family,Fantasy
4,Gone with the Wind,1939,USA,English,238,"Drama, History, Romance","Victor Fleming, George Cukor",Selznick International Pictures,A manipulative woman and a roguish man conduct...,$ 3977000,...,8.2,48047.0,230519,29565,9580,0.85,1,Drama,History,Romance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4176,Child's Play,2019,"France, Canada, USA","English, Vietnamese",90,Horror,Lars Klevberg,Orion Pictures,A mother gives her 13-year-old son a toy doll ...,$ 10000000,...,5.7,1966.0,11621,13312,3340,0.41,0,Horror,None,None
4177,Midsommar,2019,"USA, Sweden, Hungary","English, Swedish",147,"Drama, Horror, Mystery",Ari Aster,Proton Cinema,A couple travels to Sweden to visit a rural ho...,$ 10000000,...,6.7,5601.0,56527,15722,6581,0.72,1,Drama,Horror,Mystery
4178,Unplanned,2019,USA,English,109,"Biography, Drama","Chuck Konzelman, Cary Solomon",Unplanned Movie,All Abby Johnson ever wanted to do was help wo...,$ 6000000,...,6.5,2816.0,7971,403,2409,0.74,1,Biography,Drama,None
4179,Cold Blood Legacy,2019,"France, Ukraine, Belgium","French, English",91,"Action, Thriller",Frédéric Petitjean,Ascot Elite Entertainment Group,A hit-man lives isolated in a cabin at the edg...,$ 2700000,...,4.7,612.0,345,1234,614,0.16,0,Action,Thriller,None
4180,Playing with Fire,2019,USA,English,96,"Comedy, Family",Andy Fickman,Broken Road Productions,A crew of rugged firefighters meet their match...,$ 29900000,...,4.8,153.0,347,359,361,0.33,0,Comedy,Family,None

In [14]:
# Splitting country into separate columns
IMDB_movies_analysis[['country_1','country_2','country_3','rest']] = IMDB_movies_analysis['country'].str.split(",", n=3, expand=True)
IMDB_movies_analysis = IMDB_movies_analysis.drop(columns=['rest'])
IMDB_movies_analysis

,title,year,country,language,duration,genre,director,production_company,description,budget,...,neutral_votes,negative_votes,percentage_of_positive_reviews,overall_eval,genre_1,genre_2,genre_3,country_1,country_2,country_3
0,Metropolis,1927,Germany,German,153,"Drama, Sci-Fi",Fritz Lang,Universum Film (UFA),In a futuristic city sharply divided between t...,DEM 6000000,...,15050,5775,0.86,1,Drama,Sci-Fi,None,Germany,None,None
1,City Lights,1931,USA,English,87,"Comedy, Drama, Romance",Charles Chaplin,Charles Chaplin Productions,"With the aid of a wealthy erratic tippler, a d...",$ 1500000,...,10919,4453,0.90,1,Comedy,Drama,Romance,USA,None,None
2,Modern Times,1936,USA,English,87,"Comedy, Drama, Family",Charles Chaplin,Charles Chaplin Productions,The Tramp struggles to live in modern industri...,$ 1500000,...,12840,4951,0.91,1,Comedy,Drama,Family,USA,None,None
3,Snow White and the Seven Dwarfs,1937,USA,English,83,"Animation, Family, Fantasy","William Cottrell, David Hand",Walt Disney Productions,Exiled into the dangerous forest by her wicked...,$ 1499000,...,28600,3000,0.81,1,Animation,Family,Fantasy,USA,None,None
4,Gone with the Wind,1939,USA,English,238,"Drama, History, Romance","Victor Fleming, George Cukor",Selznick International Pictures,A manipulative woman and a roguish man conduct...,$ 3977000,...,29565,9580,0.85,1,Drama,History,Romance,USA,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4176,Child's Play,2019,"France, Canada, USA","English, Vietnamese",90,Horror,Lars Klevberg,Orion Pictures,A mother gives her 13-year-old son a toy doll ...,$ 10000000,...,13312,3340,0.41,0,Horror,None,None,France,Canada,USA
4177,Midsommar,2019,"USA, Sweden, Hungary","English, Swedish",147,"Drama, Horror, Mystery",Ari Aster,Proton Cinema,A couple travels to Sweden to visit a rural ho...,$ 10000000,...,15722,6581,0.72,1,Drama,Horror,Mystery,USA,Sweden,Hungary
4178,Unplanned,2019,USA,English,109,"Biography, Drama","Chuck Konzelman, Cary Solomon",Unplanned Movie,All Abby Johnson ever wanted to do was help wo...,$ 6000000,...,403,2409,0.74,1,Biography,Drama,None,USA,None,None
4179,Cold Blood Legacy,2019,"France, Ukraine, Belgium","French, English",91,"Action, Thriller",Frédéric Petitjean,Ascot Elite Entertainment Group,A hit-man lives isolated in a cabin at the edg...,$ 2700000,...,1234,614,0.16,0,Action,Thriller,None,France,Ukraine,Belgium
4180,Playing with Fire,2019,USA,English,96,"Comedy, Family",Andy Fickman,Broken Road Productions,A crew of rugged firefighters meet their match...,$ 29900000,...,359,361,0.33,0,Comedy,Family,None,USA,None,None

In [20]:
# Exporting dataframe to csv file
IMDB_movies_analysis.to_csv('IMDB_updated.csv')

In [16]:
# Creating new dataframe for currency conversions
currency_conversions = IMDB_movies_analysis[['title','budget']]
currency_conversions[['currency_symbol', 'currency_amount']] = currency_conversions['budget'].str.split(" ", expand=True)
currency_conversions.head()

,title,budget,currency_symbol,currency_amount
0,Metropolis,DEM 6000000,DEM,6000000
1,City Lights,$ 1500000,$,1500000
2,Modern Times,$ 1500000,$,1500000
3,Snow White and the Seven Dwarfs,$ 1499000,$,1499000
4,Gone with the Wind,$ 3977000,$,3977000

In [17]:
# Identifying the different currencies
currency_conversions.currency_symbol.unique()

array(['DEM', '$', 'JPY', 'AUD', 'RUR', 'GBP', 'CAD', 'FRF', 'DKK', 'SEK',
       'ATS', 'EUR', 'SGD', 'HUF', 'CNY', 'INR', 'KRW', 'NOK', 'PLN',
       'HKD', 'ARS', 'ILS', 'MXN'], dtype=object)

In [18]:
# Converting currencies into USD
for index, row in currency_conversions.iterrows():
    if row['currency_symbol'] == 'DEM':
        row['currency_amount'] = float(row['currency_amount'])*0.001740
    if row ['currency_symbol'] == 'JPY':
        row['currency_amount'] = float(row['currency_amount'])*0.0093
    if row ['currency_symbol'] == 'AUD':
        row['currency_amount'] = float(row['currency_amount'])*0.65
    if row ['currency_symbol'] == 'RUR':
        row['currency_amount'] = float(row['currency_amount'])*0.013
    if row ['currency_symbol'] == 'GBP':
        row['currency_amount'] = float(row['currency_amount'])*1.26
    if row ['currency_symbol'] == 'CAD':
        row['currency_amount'] = float(row['currency_amount'])*0.72
    if row ['currency_symbol'] == 'FRF':
        row['currency_amount'] = float(row['currency_amount'])*0.17
    if row ['currency_symbol'] == 'DKK':
        row['currency_amount'] = float(row['currency_amount'])*0.15
    if row ['currency_symbol'] == 'SEK':
        row['currency_amount'] = float(row['currency_amount'])*0.10
    if row ['currency_symbol'] == 'ATS':
        row['currency_amount'] = float(row['currency_amount'])*0.078793604651163
    if row ['currency_symbol'] == 'EUR':
        row['currency_amount'] = float(row['currency_amount'])*1.10
    if row ['currency_symbol'] == 'SGD':
        row['currency_amount'] = float(row['currency_amount'])*0.71
    if row ['currency_symbol'] == 'HUF':
        row['currency_amount'] = float(row['currency_amount'])*0.0031
    if row ['currency_symbol'] == 'CNY':
        row['currency_amount'] = float(row['currency_amount'])*0.14
    if row ['currency_symbol'] == 'INR':
        row['currency_amount'] = float(row['currency_amount'])*0.013
    if row ['currency_symbol'] == 'KRW':
        row['currency_amount'] = float(row['currency_amount'])*0.00082
    if row ['currency_symbol'] == 'PLN':
        row['currency_amount'] = float(row['currency_amount'])*0.24
    if row ['currency_symbol'] == 'HKD':
        row['currency_amount'] = float(row['currency_amount'])*0.13
    if row ['currency_symbol'] == 'ARS':
        row['currency_amount'] = float(row['currency_amount'])*0.015
    if row ['currency_symbol'] == 'ILS':
        row['currency_amount'] = float(row['currency_amount'])*0.29
    if row ['currency_symbol'] == 'MXN':
        row['currency_amount'] = float(row['currency_amount'])*0.041
    if row ['currency_symbol'] == '$':
        row['currency_amount'] = int(row['currency_amount'])

currency_conversions.head()

,title,budget,currency_symbol,currency_amount
0,Metropolis,DEM 6000000,DEM,10440
1,City Lights,$ 1500000,$,1500000
2,Modern Times,$ 1500000,$,1500000
3,Snow White and the Seven Dwarfs,$ 1499000,$,1499000
4,Gone with the Wind,$ 3977000,$,3977000

In [19]:
# Export dataframe to csv file
currency_conversions.to_csv('currencyConversions.csv')

In [ ]:
# sentiment_breakdown = IMDB_movies_analysis
# sentiment_breakdown

In [ ]:
# sentiment_breakdown[['bad','good']] = pd.get_dummies(sentiment_breakdown['overall_evaluation'])
# sentiment_breakdown

In [ ]:
# sentiment_breakdown.to_csv('IMDB_updated.csv')

In [ ]:
# from sklearn.model_selection import train_test_split 
# y = test[['good','bad']]
# X = test[['metascore','duration']]
# print(X.shape, y.shape)

In [ ]:
# X_train,X_test,y_train, y_test = train_test_split(X,y, random_state = 1, stratify =y)

In [ ]:
# y_test

In [ ]:
# from sklearn.preprocessing import MinMaxScaler
# X_scaler = MinMaxScaler().fit(X_train)
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# from sklearn.svm import SVC
# model2 = SVC(kernel = "linear")
# model2.fit(X_train_scaled, y_train)